name: Spring boot mybatis
rating: 5
imageUrl: https://github.com/msa-ez/template-spring-boot-3/assets/123912988/a901ad8f-7548-42db-b4a4-67a34bfd9279
templateName: spring-boot-mybatis
description: Provides an environment to simplify and efficiently handle database query and mapping tasks.
group: Spring boot
